In [26]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv('/Users/areum/Documents/ISLR/Caravan.csv', index_col=0)

In [29]:
df.head()

MOSTYPE  MAANTHUI  MGEMOMV  MGEMLEEF  MOSHOOFD  MGODRK  MGODPR  MGODOV  \
1       33         1        3         2         8       0       5       1   
2       37         1        2         2         8       1       4       1   
3       37         1        2         2         8       0       4       2   
4        9         1        3         3         3       2       3       2   
5       40         1        4         2        10       1       4       1   

   MGODGE  MRELGE    ...     APERSONG  AGEZONG  AWAOREG  ABRAND  AZEILPL  \
1       3       7    ...            0        0        0       1        0   
2       4       6    ...            0        0        0       1        0   
3       4       3    ...            0        0        0       1        0   
4       4       5    ...            0        0        0       1        0   
5       4       7    ...            0        0        0       1        0   

   APLEZIER  AFIETS  AINBOED  ABYSTAND  Purchase  
1         0       0        0         0        No  
2         0       0        0         0        No  
3         0       0        0         0        No  
4         0       0        0         0        No  
5         0       0        0         0        No  

[5 rows x 86 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5822 entries, 1 to 5822
Data columns (total 86 columns):
MOSTYPE     5822 non-null int64
MAANTHUI    5822 non-null int64
MGEMOMV     5822 non-null int64
MGEMLEEF    5822 non-null int64
MOSHOOFD    5822 non-null int64
MGODRK      5822 non-null int64
MGODPR      5822 non-null int64
MGODOV      5822 non-null int64
MGODGE      5822 non-null int64
MRELGE      5822 non-null int64
MRELSA      5822 non-null int64
MRELOV      5822 non-null int64
MFALLEEN    5822 non-null int64
MFGEKIND    5822 non-null int64
MFWEKIND    5822 non-null int64
MOPLHOOG    5822 non-null int64
MOPLMIDD    5822 non-null int64
MOPLLAAG    5822 non-null int64
MBERHOOG    5822 non-null int64
MBERZELF    5822 non-null int64
MBERBOER    5822 non-null int64
MBERMIDD    5822 non-null int64
MBERARBG    5822 non-null int64
MBERARBO    5822 non-null int64
MSKA        5822 non-null int64
MSKB1       5822 non-null int64
MSKB2       5822 non-null int64
MSKC        5822 non-null int

In [31]:
df.describe()

MOSTYPE     MAANTHUI      MGEMOMV     MGEMLEEF     MOSHOOFD  \
count  5822.000000  5822.000000  5822.000000  5822.000000  5822.000000   
mean     24.253349     1.110615     2.678805     2.991240     5.773617   
std      12.846706     0.405842     0.789835     0.814589     2.856760   
min       1.000000     1.000000     1.000000     1.000000     1.000000   
25%      10.000000     1.000000     2.000000     2.000000     3.000000   
50%      30.000000     1.000000     3.000000     3.000000     7.000000   
75%      35.000000     1.000000     3.000000     3.000000     8.000000   
max      41.000000    10.000000     5.000000     6.000000    10.000000   

            MGODRK       MGODPR       MGODOV       MGODGE       MRELGE  \
count  5822.000000  5822.000000  5822.000000  5822.000000  5822.000000   
mean      0.696496     4.626932     1.069907     3.258502     6.183442   
std       1.003234     1.715843     1.017503     1.597647     1.909482   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     4.000000     0.000000     2.000000     5.000000   
50%       0.000000     5.000000     1.000000     3.000000     6.000000   
75%       1.000000     6.000000     2.000000     4.000000     7.000000   
max       9.000000     9.000000     5.000000     9.000000     9.000000   

          ...            ALEVEN     APERSONG      AGEZONG      AWAOREG  \
count     ...       5822.000000  5822.000000  5822.000000  5822.000000   
mean      ...          0.076606     0.005325     0.006527     0.004638   
std       ...          0.377569     0.072782     0.080532     0.077403   
min       ...          0.000000     0.000000     0.000000     0.000000   
25%       ...          0.000000     0.000000     0.000000     0.000000   
50%       ...          0.000000     0.000000     0.000000     0.000000   
75%       ...          0.000000     0.000000     0.000000     0.000000   
max       ...          8.000000     1.000000     1.000000     2.000000   

            ABRAND      AZEILPL     APLEZIER       AFIETS      AINBOED  \
count  5822.000000  5822.000000  5822.000000  5822.000000  5822.000000   
mean      0.570079     0.000515     0.006012     0.031776     0.007901   
std       0.562058     0.022696     0.081632     0.210986     0.090463   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     0.000000     0.000000     0.000000   
max       7.000000     1.000000     2.000000     3.000000     2.000000   

          ABYSTAND  
count  5822.000000  
mean      0.014256  
std       0.119996  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       2.000000  

[8 rows x 85 columns]

In [44]:
X = df.iloc[:,:-1].astype('float64')
y = df['Purchase'].values

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
scale = StandardScaler()

In [47]:
X_scaled = scale.fit_transform(X)

In [48]:
X_scaled.shape

(5822, 85)

In [67]:
X_train = X_scaled[1000:,:]
y_train = y[1000:]

In [68]:
X_test = X_scaled[:1000,:]
y_test = y[:1000]

In [81]:
from sklearn.neighbors import KNeighborsClassifier

In [82]:
knn = KNeighborsClassifier(n_neighbors=1)

In [83]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [84]:
pred = knn.predict(X_test)

In [85]:
from sklearn.metrics import classification_report, confusion_matrix

In [86]:
print(classification_report(y_test, pred, digits=3))

             precision    recall  f1-score   support

         No      0.946     0.928     0.937       941
        Yes      0.117     0.153     0.132        59

avg / total      0.897     0.882     0.889      1000



In [87]:
print(confusion_matrix(y_test, pred))

[[873  68]
 [ 50   9]]


In [92]:
(y_test != pred).mean()

0.11799999999999999

In [95]:
(y_test != 'No').mean()

0.058999999999999997

In [99]:
for i in range(1,100):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred = knn.predict(X_test)
    print("n_neighbors: ", i)
    print(classification_report(y_test, pred, digits=3))
    print(confusion_matrix(y_test, pred).T)
    print((y_test != pred).mean())
    print((y_test != 'No').mean())
    print("\n")

n_neighbors:  1
             precision    recall  f1-score   support

         No      0.946     0.928     0.937       941
        Yes      0.117     0.153     0.132        59

avg / total      0.897     0.882     0.889      1000

[[873  50]
 [ 68   9]]
0.118
0.059


n_neighbors:  2
             precision    recall  f1-score   support

         No      0.940     0.990     0.965       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.932     0.908      1000

[[932  59]
 [  9   0]]
0.068
0.059


n_neighbors:  3
             precision    recall  f1-score   support

         No      0.945     0.979     0.961       941
        Yes      0.200     0.085     0.119        59

avg / total      0.901     0.926     0.912      1000

[[921  54]
 [ 20   5]]
0.074
0.059


n_neighbors:  4
             precision    recall  f1-score   support

         No      0.941     0.995     0.967       941
        Yes      0.000     0.000     0.000        59

avg / total      0.

/Users/areum/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


n_neighbors:  9
             precision    recall  f1-score   support

         No      0.942     1.000     0.970       941
        Yes      1.000     0.017     0.033        59

avg / total      0.945     0.942     0.915      1000

[[941  58]
 [  0   1]]
0.058
0.059


n_neighbors:  10
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.941     0.912      1000

[[941  59]
 [  0   0]]
0.059
0.059


n_neighbors:  11
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.941     0.912      1000

[[941  59]
 [  0   0]]
0.059
0.059


n_neighbors:  12
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total     

n_neighbors:  40
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.941     0.912      1000

[[941  59]
 [  0   0]]
0.059
0.059


n_neighbors:  41
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.941     0.912      1000

[[941  59]
 [  0   0]]
0.059
0.059


n_neighbors:  42
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.941     0.912      1000

[[941  59]
 [  0   0]]
0.059
0.059


n_neighbors:  43
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total    

n_neighbors:  71
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.941     0.912      1000

[[941  59]
 [  0   0]]
0.059
0.059


n_neighbors:  72
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.941     0.912      1000

[[941  59]
 [  0   0]]
0.059
0.059


n_neighbors:  73
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.941     0.912      1000

[[941  59]
 [  0   0]]
0.059
0.059


n_neighbors:  74
             precision    recall  f1-score   support

         No      0.941     1.000     0.970       941
        Yes      0.000     0.000     0.000        59

avg / total    

In [80]:
df.groupby('Purchase')['Purchase'].count() / df.Purchase.count()

Purchase
No     0.940227
Yes    0.059773
Name: Purchase, dtype: float64

## Logistic

In [100]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

/Users/areum/anaconda/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [104]:
from sklearn.linear_model import LogisticRegression

In [105]:
log = LogisticRegression()

In [106]:
log.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [107]:
log_pred = log.predict(X_test)

In [111]:
print(classification_report(y_test, log_pred, digits=3))

             precision    recall  f1-score   support

         No      0.941     0.993     0.966       941
        Yes      0.000     0.000     0.000        59

avg / total      0.885     0.934     0.909      1000



In [113]:
print(confusion_matrix(y_test, log_pred).T)

[[934  59]
 [  7   0]]


In [177]:
y_test_proba = log.predict_proba(X_test)

In [193]:
y_test_proba[:,:]

array([[ 0.90264908,  0.09735092],
       [ 0.98828572,  0.01171428],
       [ 0.94366315,  0.05633685],
       ..., 
       [ 0.9782849 ,  0.0217151 ],
       [ 0.83881746,  0.16118254],
       [ 0.96884334,  0.03115666]])

In [196]:
y_test_proba[:,1]

array([  9.73509233e-02,   1.17142848e-02,   5.63368529e-02,
         9.95884625e-02,   3.15175487e-02,   1.81992787e-02,
         3.95073796e-02,   8.59009357e-03,   3.56279976e-02,
         2.23449098e-02,   9.64543618e-02,   8.72580923e-02,
         6.04603436e-02,   1.66047762e-02,   3.55678771e-02,
         2.73088189e-02,   2.08683599e-02,   7.35388383e-02,
         1.07012271e-01,   8.15850935e-03,   2.37465618e-02,
         7.53296421e-02,   1.65220384e-01,   9.93600297e-03,
         5.01311257e-02,   3.48998922e-02,   1.07802871e-01,
         6.85462840e-03,   1.32643631e-03,   1.15098817e-02,
         6.16565095e-02,   2.41556834e-02,   7.59437881e-02,
         1.40664377e-02,   3.51374946e-02,   8.76239322e-02,
         2.78864488e-01,   1.35555116e-02,   2.23507353e-02,
         7.19457047e-02,   8.47181098e-03,   2.01764252e-01,
         4.96929565e-02,   3.64520274e-02,   5.82580724e-02,
         6.12056163e-02,   2.11734664e-02,   6.61852416e-02,
         7.99975549e-02,

In [197]:
upper_thres = ['Yes' if x > 0.5 else 'No' for x in y_test_proba[:,1]]

In [198]:
lower_thres = ['Yes' if x > 0.25 else 'No' for x in y_test_proba[:,1]]

In [200]:
print(classification_report(y_test, lower_thres, digits=3))

             precision    recall  f1-score   support

         No      0.950     0.974     0.962       941
        Yes      0.314     0.186     0.234        59

avg / total      0.913     0.928     0.919      1000



In [201]:
print(confusion_matrix(y_test, lower_thres).T)

[[917  48]
 [ 24  11]]
