In [1]:
pwd

'/Users/areum'

In [2]:
cd '/Users/areum/Documents/ISLR/'

/Users/areum/Documents/ISLR


In [3]:
ls

Auto.csv                  classification 4.pdf      nonlinear 7.pdf
Boston.csv                cv_boot 5.pdf             statistical_learning.pdf
Carseats.csv              introduction.pdf          svm 9.pdf
boston.ipynb              linear_regression 3.pdf   trees 8.pdf
boston.txt                model_selection 6.pdf     unsupervised 10.pdf


In [30]:
import pandas as pd
import numpy as np

In [31]:
from bokeh.plotting import figure
from bokeh.io import show, output_file

In [32]:
df = pd.read_csv('Auto.csv')

In [33]:
df.head()

Unnamed: 0   mpg  cylinders  displacement  horsepower  weight  \
0           1  18.0          8         307.0         130    3504   
1           2  15.0          8         350.0         165    3693   
2           3  18.0          8         318.0         150    3436   
3           4  16.0          8         304.0         150    3433   
4           5  17.0          8         302.0         140    3449   

   acceleration  year  origin                       name  
0          12.0    70       1  chevrolet chevelle malibu  
1          11.5    70       1          buick skylark 320  
2          11.0    70       1         plymouth satellite  
3          12.0    70       1              amc rebel sst  
4          10.5    70       1                ford torino

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 10 columns):
Unnamed: 0      392 non-null int64
mpg             392 non-null float64
cylinders       392 non-null int64
displacement    392 non-null float64
horsepower      392 non-null int64
weight          392 non-null int64
acceleration    392 non-null float64
year            392 non-null int64
origin          392 non-null int64
name            392 non-null object
dtypes: float64(3), int64(6), object(1)
memory usage: 30.7+ KB


In [34]:
X = df.horsepower
y = df.mpg
X1 = sm.add_constant(X)

In [35]:
import statsmodels.api as sm

In [36]:
lin = sm.OLS(endog=y, exog=X1).fit()

In [37]:
print(lin.summary())

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.606
Model:                            OLS   Adj. R-squared:                  0.605
Method:                 Least Squares   F-statistic:                     599.7
Date:                Thu, 01 Feb 2018   Prob (F-statistic):           7.03e-81
Time:                        21:45:42   Log-Likelihood:                -1178.7
No. Observations:                 392   AIC:                             2361.
Df Residuals:                     390   BIC:                             2369.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const         39.9359      0.717     55.660      0.0

In [38]:
b0 = lin.params[0]
b1 = lin.params[1]

In [39]:
b0

39.935861021170467

In [40]:
b1

-0.15784473335365357

In [42]:
p = figure()
p.circle(X, y)
p.line(X, b0 + b1*X, color='red')
show(p)

In [44]:
np.percentile(X, [2.5, 97.5])

array([  52.775,  201.8  ])

In [46]:
b0 + b1 * 98

24.467077152512417

In [54]:
y_pred = b0 + b1*X

In [62]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y, b0 + b1*X)

23.943662938603108

In [68]:
from sklearn.linear_model import LinearRegression

In [69]:
lin_r = LinearRegression()

In [73]:
X = X.reshape(-1, 1)
y = y.reshape(-1, 1)

/Users/areum/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.
/Users/areum/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  


In [74]:
lin_r.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [75]:
y_pred = lin_r.predict(X)

In [93]:
RSS = sum((y - y_pred)**2)
RSE = np.sqrt(RSS/390)
print('RSE: ', RSE)

RSE:  [ 4.90575692]


In [101]:
r_squared = lin_r.score(X, y)

In [112]:
from sklearn.metrics import mean_squared_error

rms = np.sqrt(mean_squared_error(y, y_pred))

In [114]:
mean_squared_error(y, y_pred)

23.943662938603108

In [119]:
from scipy import stats

mu = np.mean(y)
pred_mu = np.mean(y_pred)

sigma = np.std(y)
pred_sigma = np.std(y_pred)

stats.norm.interval(0.95, loc=mu, scale=sigma)

(8.1679094146475162, 38.723927320046357)

In [147]:
stats.norm.interval(0.95, loc=np.mean(y), scale=np.std(y))

(8.1679094146475162, 38.723927320046357)

In [148]:
stats.norm.interval(0.95, loc=np.mean(y_pred), scale=np.std(y_pred))

(11.5531069939357, 35.338729740758176)

In [123]:
np.percentile(y, [2.5, 97.5])

array([ 12.    ,  39.0225])

In [124]:
np.percentile(y_pred, [2.5, 97.5])

array([  8.08279383,  31.60560522])

In [128]:
#predict(fit.lm, new, interval = "confidence")  # conf interval
##        fit      lwr      upr
## 1 24.46708 23.97308 24.96108

#predict(fit.lm, new, interval = "prediction")  # pred interval
##        fit     lwr      upr
## 1 24.46708 14.8094 34.12476

In [133]:
lin.conf_int(0.05)

0          1
const       38.525212  41.346510
horsepower  -0.170517  -0.145172

In [143]:
np.percentile(lin_r.predict(X), [2.5, 97.5])

array([  8.08279383,  31.60560522])

In [150]:
np.std(y)/np.sqrt(len(y))*1.96

0.7716701605833246

In [151]:
np.mean(y) + (np.std(y)/np.sqrt(len(y))*1.96)

24.217588527930261

In [152]:
np.mean(y) - (np.std(y)/np.sqrt(len(y))*1.96)

22.674248206763615

In [153]:
np.mean(y_pred) + (np.std(y_pred)/np.sqrt(len(y_pred))*1.96)

24.046607088679696

In [154]:
np.mean(y_pred) - (np.std(y_pred)/np.sqrt(len(y_pred))*1.96)

22.845229646014179

In [156]:
np.mean(X) + (np.std(X)/np.sqrt(len(X))*1.96)

108.27495483719724